//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 声音设置 的本地化字符串。
        /// </summary>
        public static string AudioSettings {
            get {
                return ResourceManager.GetString("AudioSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏音量 的本地化字符串。
        /// </summary>
        public static string BGM {
            get {
                return ResourceManager.GetString("BGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简单 的本地化字符串。
        /// </summary>
        public static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 困难 的本地化字符串。
        /// </summary>
        public static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口化 的本地化字符串。
        /// </summary>
        public static string IsWindow {
            get {
                return ResourceManager.GetString("IsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动器 的本地化字符串。
        /// </summary>
        public static string Launcher {
            get {
                return ResourceManager.GetString("Launcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务 的本地化字符串。
        /// </summary>
        public static string Mission {
            get {
                return ResourceManager.GetString("Mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无边框 的本地化字符串。
        /// </summary>
        public static string NoFrame {
            get {
                return ResourceManager.GetString("NoFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 普通 的本地化字符串。
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始行动 的本地化字符串。
        /// </summary>
        public static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分辨率 的本地化字符串。
        /// </summary>
        public static string Screen {
            get {
                return ResourceManager.GetString("Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 特效音量 的本地化字符串。
        /// </summary>
        public static string SEM {
            get {
                return ResourceManager.GetString("SEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简报 的本地化字符串。
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ====Crape Launcher==== 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用图形API兼容模式 的本地化字符串。
        /// </summary>
        public static string UseGraphicsAPI {
            get {
                return ResourceManager.GetString("UseGraphicsAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示设置 的本地化字符串。
        /// </summary>
        public static string VideoSettings {
            get {
                return ResourceManager.GetString("VideoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语音音量 的本地化字符串。
        /// </summary>
        public static string VOX {
            get {
                return ResourceManager.GetString("VOX", resourceCulture);
            }
        }
    }
}
